/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTimerSessionRequest {
  timer_id: string;
  started_at?: string;
  /** @nullable */
  ended_at?: string | null;
  source?: string;
  /** @nullable */
  note?: string | null;
}
