/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTimerRequest {
  /** @minLength 1 */
  timer_type: string;
  /** Timer category ID (Useful, Important, Procrastination, or custom) */
  category_id?: string;
  /** @minLength 1 */
  name: string;
  /** Ionicons icon name */
  icon?: string;
  color?: string;
  /** Minimum session duration in seconds */
  min_time?: number;
  is_archived?: boolean;
}
