/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTimerCategoryRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  color: string;
}
