/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1ExampleDb200 = {
  data: string;
};
