/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1TimersParams = {
/**
 * Date in YYYY-MM-DD format. When provided, total_timer_session_time is computed for that day. Omit for today.
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
date?: string;
};
