/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1TimersIdStatsParams = {
/**
 * Start date in YYYY-MM-DD format (DateOnly, optional)
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
start_date?: string;
/**
 * End date in YYYY-MM-DD format (DateOnly, optional)
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
end_date?: string;
};
