/**
 * Manual addition for date param - will be generated by orval when gen:api succeeds
 */

export type GetApiV1TimersParams = {
  /**
   * Date in YYYY-MM-DD format. When provided, total_timer_session_time is computed for that day.
   */
  date?: string;
};
