/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface ReorderTimersRequest {
  /**
   * Timer IDs in desired order; index 0 = sort_order 0
   * @minItems 1
   */
  timer_ids: string[];
}
