/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */
import type { TimerSessionInProgress } from './timerSessionInProgress';
import type { TimerTimerSessionInProgressAllOf } from './timerTimerSessionInProgressAllOf';

export type TimerTimerSessionInProgress = TimerSessionInProgress & TimerTimerSessionInProgressAllOf;
