/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface TimerSession {
  id: string;
  user_id: string;
  timer_id: string;
  started_at: string;
  /** @nullable */
  ended_at: string | null;
  /** @nullable */
  original_started_at: string | null;
  /** @nullable */
  original_ended_at: string | null;
  source: string;
  /** @nullable */
  note: string | null;
  is_deleted: boolean;
  created_at: string;
  updated_at: string;
  /** @nullable */
  updated_by: string | null;
}
