/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface TimerStatsDay {
  /**
   * Date in YYYY-MM-DD format (DateOnly)
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  date: string;
  /** Total timer session time for this day in seconds */
  total_timer_session_time: number;
}
