/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

/**
 * The timer session currently in progress (started_at set, no ended_at), or null
 * @nullable
 */
export type TimerTimerSessionInProgressAllOf = unknown | null;
