/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

/**
 * The timer's category (Useful, Important, Procrastination, or custom)
 * @nullable
 */
export type TimerCategory = {
  id: string;
  /**
   * Null for system categories
   * @nullable
   */
  user_id: string | null;
  name: string;
  color: string;
  sort_order: number;
} | null;
