/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */
import type { TimerStatsDay } from './timerStatsDay';

export interface TimerStatsResponse {
  data: TimerStatsDay[];
}
