/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface Timer {
  id: string;
  user_id: string;
  timer_type: string;
  name: string;
  /** @nullable */
  color: string | null;
  sort_order: number;
  is_archived: boolean;
  is_deleted: boolean;
  created_at: string;
  updated_at: string;
  /** @nullable */
  updated_by: string | null;
  /** Total timer session time for current day in seconds */
  total_timer_session_time: number;
  /**
   * ID of the last timer session that has started_at but no ended_at
   * @nullable
   */
  timer_session_in_progress_id: string | null;
}
