/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */
import type { TimerCategory } from './timerCategory';
import type { TimerTimerSessionInProgress } from './timerTimerSessionInProgress';

export interface Timer {
  id: string;
  user_id: string;
  timer_type: string;
  /** @nullable */
  category_id: string | null;
  category: TimerCategory;
  name: string;
  /** @nullable */
  color: string | null;
  sort_order: number;
  /**
   * Minimum session duration in seconds
   * @nullable
   */
  min_time: number | null;
  is_archived: boolean;
  is_deleted: boolean;
  created_at: string;
  updated_at: string;
  /** @nullable */
  updated_by: string | null;
  /** Total timer session time for current day in seconds */
  total_timer_session_time: number;
  /** Null when no session is running for this timer */
  timer_session_in_progress: TimerTimerSessionInProgress | null;
}
