/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTimerRequest {
  /** @minLength 1 */
  name?: string;
  color?: string;
  /**
   * Minimum session duration in seconds
   * @nullable
   */
  min_time?: number | null;
  is_archived?: boolean;
  /** @minLength 1 */
  timer_type?: string;
  /**
   * Timer category ID or null to clear
   * @nullable
   */
  category_id?: string | null;
}
