/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProfileRequest {
  first_name?: string;
  last_name?: string;
  timezone?: string;
  language?: string | null;
}
