/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Timeflow API
 * API for the Timeflow application
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTimerSessionRequest {
  /** Edit session start time (user correction). Send with ended_at for full edit. */
  started_at?: string;
  /**
   * End session (if not yet ended) or edit end time. Required when ending; optional for edit.
   * @nullable
   */
  ended_at?: string | null;
}
